// <auto-generated />
namespace PeopleProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddoverridePropertyInDBContext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddoverridePropertyInDBContext));
        
        string IMigrationMetadata.Id
        {
            get { return "201702132355547_AddoverridePropertyInDBContext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
